name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and build on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -ex
            cd /root/projects/XPM_front
            git pull origin master
            npm install
            npm run build
            if [ -d /root/projects/XPM_front/dist ]; then
                cd
                sudo rm -rf /var/www/html/dist
                sudo cp -r /root/projects/XPM_front/dist /var/www/html/
            else
                echo "Build directory does not exist, skipping copy"
                exit 1
            fi
            sudo systemctl reload nginx
